/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContentId = bigint;
export type ContentMode = { 'chat' : null } |
  { 'coding' : null } |
  { 'paragraph' : null };
export type Language = { 'hinglish' : null } |
  { 'english' : null };
export type SessionId = bigint;
export interface SessionStats {
  'id' : SessionId,
  'wpm' : bigint,
  'difficulty' : bigint,
  'mode' : ContentMode,
  'language' : Language,
  'timestamp' : Timestamp,
  'mistakesCount' : bigint,
  'accuracy' : number,
}
export interface StreakData {
  'lastSessionDate' : string,
  'currentStreak' : bigint,
}
export type Timestamp = bigint;
export interface TypingContent {
  'id' : ContentId,
  'difficulty' : bigint,
  'mode' : ContentMode,
  'text' : string,
  'language' : Language,
  'category' : string,
}
export interface _SERVICE {
  'getContent' : ActorMethod<[string, string, bigint], Array<TypingContent>>,
  'getRandomContent' : ActorMethod<
    [string, string, bigint],
    [] | [TypingContent]
  >,
  'getSessions' : ActorMethod<[], Array<SessionStats>>,
  'getStreak' : ActorMethod<[], StreakData>,
  'saveSession' : ActorMethod<
    [bigint, number, string, string, bigint, bigint, bigint],
    undefined
  >,
  'updateStreak' : ActorMethod<[string], StreakData>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];