/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContentId = IDL.Nat;
export const ContentMode = IDL.Variant({
  'chat' : IDL.Null,
  'coding' : IDL.Null,
  'paragraph' : IDL.Null,
});
export const Language = IDL.Variant({
  'hinglish' : IDL.Null,
  'english' : IDL.Null,
});
export const TypingContent = IDL.Record({
  'id' : ContentId,
  'difficulty' : IDL.Nat,
  'mode' : ContentMode,
  'text' : IDL.Text,
  'language' : Language,
  'category' : IDL.Text,
});
export const SessionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const SessionStats = IDL.Record({
  'id' : SessionId,
  'wpm' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'mode' : ContentMode,
  'language' : Language,
  'timestamp' : Timestamp,
  'mistakesCount' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const StreakData = IDL.Record({
  'lastSessionDate' : IDL.Text,
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(TypingContent)],
      ['query'],
    ),
  'getRandomContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(TypingContent)],
      ['query'],
    ),
  'getSessions' : IDL.Func([], [IDL.Vec(SessionStats)], ['query']),
  'getStreak' : IDL.Func([], [StreakData], ['query']),
  'saveSession' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Nat, IDL.Int, IDL.Nat],
      [],
      [],
    ),
  'updateStreak' : IDL.Func([IDL.Text], [StreakData], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContentId = IDL.Nat;
  const ContentMode = IDL.Variant({
    'chat' : IDL.Null,
    'coding' : IDL.Null,
    'paragraph' : IDL.Null,
  });
  const Language = IDL.Variant({ 'hinglish' : IDL.Null, 'english' : IDL.Null });
  const TypingContent = IDL.Record({
    'id' : ContentId,
    'difficulty' : IDL.Nat,
    'mode' : ContentMode,
    'text' : IDL.Text,
    'language' : Language,
    'category' : IDL.Text,
  });
  const SessionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const SessionStats = IDL.Record({
    'id' : SessionId,
    'wpm' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'mode' : ContentMode,
    'language' : Language,
    'timestamp' : Timestamp,
    'mistakesCount' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const StreakData = IDL.Record({
    'lastSessionDate' : IDL.Text,
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    'getContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(TypingContent)],
        ['query'],
      ),
    'getRandomContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(TypingContent)],
        ['query'],
      ),
    'getSessions' : IDL.Func([], [IDL.Vec(SessionStats)], ['query']),
    'getStreak' : IDL.Func([], [StreakData], ['query']),
    'saveSession' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Nat, IDL.Int, IDL.Nat],
        [],
        [],
      ),
    'updateStreak' : IDL.Func([IDL.Text], [StreakData], []),
  });
};

export const init = ({ IDL }) => { return []; };