/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StreakData {
    lastSessionDate: string;
    currentStreak: bigint;
}
export type Timestamp = bigint;
export type ContentId = bigint;
export interface SessionStats {
    id: SessionId;
    wpm: bigint;
    difficulty: bigint;
    mode: ContentMode;
    language: Language;
    timestamp: Timestamp;
    mistakesCount: bigint;
    accuracy: number;
}
export type SessionId = bigint;
export interface TypingContent {
    id: ContentId;
    difficulty: bigint;
    mode: ContentMode;
    text: string;
    language: Language;
    category: string;
}
export enum ContentMode {
    chat = "chat",
    coding = "coding",
    paragraph = "paragraph"
}
export enum Language {
    hinglish = "hinglish",
    english = "english"
}
export interface backendInterface {
    getContent(mode: string, language: string, difficulty: bigint): Promise<Array<TypingContent>>;
    getRandomContent(mode: string, language: string, difficulty: bigint): Promise<TypingContent | null>;
    getSessions(): Promise<Array<SessionStats>>;
    getStreak(): Promise<StreakData>;
    saveSession(wpm: bigint, accuracy: number, mode: string, language: string, difficulty: bigint, timestamp: bigint, mistakesCount: bigint): Promise<void>;
    updateStreak(today: string): Promise<StreakData>;
}
import type { ContentId as _ContentId, ContentMode as _ContentMode, Language as _Language, SessionId as _SessionId, SessionStats as _SessionStats, Timestamp as _Timestamp, TypingContent as _TypingContent } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getContent(arg0: string, arg1: string, arg2: bigint): Promise<Array<TypingContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContent(arg0, arg1, arg2);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContent(arg0, arg1, arg2);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomContent(arg0: string, arg1: string, arg2: bigint): Promise<TypingContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomContent(arg0, arg1, arg2);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomContent(arg0, arg1, arg2);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessions(): Promise<Array<SessionStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessions();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessions();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreak(): Promise<StreakData> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreak();
            return result;
        }
    }
    async saveSession(arg0: bigint, arg1: number, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSession(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSession(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateStreak(arg0: string): Promise<StreakData> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStreak(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStreak(arg0);
            return result;
        }
    }
}
function from_candid_ContentMode_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentMode): ContentMode {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStats_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStats): SessionStats {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TypingContent_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TypingContent): TypingContent {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TypingContent]): TypingContent | null {
    return value.length === 0 ? null : from_candid_TypingContent_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    wpm: bigint;
    difficulty: bigint;
    mode: _ContentMode;
    language: _Language;
    timestamp: _Timestamp;
    mistakesCount: bigint;
    accuracy: number;
}): {
    id: SessionId;
    wpm: bigint;
    difficulty: bigint;
    mode: ContentMode;
    language: Language;
    timestamp: Timestamp;
    mistakesCount: bigint;
    accuracy: number;
} {
    return {
        id: value.id,
        wpm: value.wpm,
        difficulty: value.difficulty,
        mode: from_candid_ContentMode_n4(_uploadFile, _downloadFile, value.mode),
        language: from_candid_Language_n6(_uploadFile, _downloadFile, value.language),
        timestamp: value.timestamp,
        mistakesCount: value.mistakesCount,
        accuracy: value.accuracy
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ContentId;
    difficulty: bigint;
    mode: _ContentMode;
    text: string;
    language: _Language;
    category: string;
}): {
    id: ContentId;
    difficulty: bigint;
    mode: ContentMode;
    text: string;
    language: Language;
    category: string;
} {
    return {
        id: value.id,
        difficulty: value.difficulty,
        mode: from_candid_ContentMode_n4(_uploadFile, _downloadFile, value.mode),
        text: value.text,
        language: from_candid_Language_n6(_uploadFile, _downloadFile, value.language),
        category: value.category
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chat: null;
} | {
    coding: null;
} | {
    paragraph: null;
}): ContentMode {
    return "chat" in value ? ContentMode.chat : "coding" in value ? ContentMode.coding : "paragraph" in value ? ContentMode.paragraph : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hinglish: null;
} | {
    english: null;
}): Language {
    return "hinglish" in value ? Language.hinglish : "english" in value ? Language.english : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TypingContent>): Array<TypingContent> {
    return value.map((x)=>from_candid_TypingContent_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionStats>): Array<SessionStats> {
    return value.map((x)=>from_candid_SessionStats_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
